name = "revolt-pass"
main = "src/worker/index.ts"
compatibility_date = "2024-09-01"
compatibility_flags = ["nodejs_compat"]

# Dominio personalizado de producción y workers.dev activo
workers_dev = true
routes = [
  { pattern = "pass.revoltgroup.com.ar", custom_domain = true }
]

# Servir frontend estático compilado por Vite
[assets]
directory = "./dist"
binding = "ASSETS"

[[d1_databases]]
binding = "DB"
database_name = "revolt-pass-db"
database_id = "71e43d83-619e-4d92-8e89-d17eaef9f439"

# Variables de entorno públicas
[vars]
ENVIRONMENT = "production"
APP_NAME = "Revolt Pass"
APP_DOMAIN = "https://pass.revoltgroup.com.ar"
