import { sanitizeBase32, isValidBase32 } from '../crypto/base32';
import type { ImportedAccount, ImportResult } from './types';

/**
 * Parses Authy token exports (JSON format generated by community export tools or DevTools).
 */
export function parseAuthyExport(jsonContent: string): ImportResult {
  const warnings: string[] = [];
  const accounts: ImportedAccount[] = [];

  let parsed: unknown;
  try {
    parsed = JSON.parse(jsonContent);
  } catch {
    return {
      platform: 'authy',
      platformLabel: 'Authy (Twilio)',
      accounts: [],
      warnings: ['El contenido no es un JSON válido'],
    };
  }

  let rawList: unknown[] = [];
  if (Array.isArray(parsed)) {
    rawList = parsed;
  } else if (parsed && typeof parsed === 'object') {
    const obj = parsed as Record<string, unknown>;
    if (Array.isArray(obj.authenticator_tokens)) {
      rawList = obj.authenticator_tokens;
    } else if (Array.isArray(obj.tokens)) {
      rawList = obj.tokens;
    } else if (Array.isArray(obj.items)) {
      rawList = obj.items;
    }
  }

  if (rawList.length === 0) {
    return {
      platform: 'authy',
      platformLabel: 'Authy (Twilio)',
      accounts: [],
      warnings: ['No se encontraron tokens en la estructura exportada de Authy'],
    };
  }

  for (let i = 0; i < rawList.length; i++) {
    const item = rawList[i];
    if (!item || typeof item !== 'object') continue;

    const row = item as Record<string, unknown>;
    const rawSecret = String(
      row.decrypted_secret ||
      row.decryptedSecret ||
      row.secret_seed ||
      row.secretSeed ||
      row.secret ||
      ''
    ).trim();

    if (!rawSecret) {
      warnings.push(`Elemento #${i + 1} omitido: no contiene clave secreta descifrada.`);
      continue;
    }

    const sanitizedSecret = sanitizeBase32(rawSecret);
    if (!isValidBase32(sanitizedSecret)) {
      warnings.push(`Elemento #${i + 1} ("${row.name || 'Sin nombre'}"): secreto Base32 inválido.`);
      continue;
    }

    let name = String(row.name || row.account_name || row.original_name || 'Cuenta Authy').trim();
    let issuer = String(row.issuer || row.original_name || '').trim();

    if (!issuer && name.includes(':')) {
      const parts = name.split(':');
      issuer = parts[0].trim();
      name = parts.slice(1).join(':').trim();
    }
    if (!issuer) {
      issuer = name;
    }

    const digits = Number(row.digits) === 8 ? 8 : 6;
    const period = Number(row.period) || 30;

    accounts.push({
      name: name || 'Cuenta Authy',
      issuer: issuer || 'Authy',
      secret: sanitizedSecret,
      type: 'totp',
      algorithm: 'SHA1',
      digits,
      period,
      platform: 'authy',
    });
  }

  return {
    platform: 'authy',
    platformLabel: 'Authy (Twilio)',
    accounts,
    warnings,
  };
}
